<?php
/*
Plugin Name: Athena Shortcodes
Version: 0.3.2
Author: UCF Web Communications
Description: Provides shortcodes for use with the Athena-Framework.
Plugin URL: https://github.com/UCF/Athena-Shortcodes-Plugin/
Tags: athena-framework,shortcodes
*/
if ( ! defined( 'WPINC' ) ) {
	die;
}

define( 'ATHENA_SC__PLUGIN_FILE', __FILE__ );
define( 'ATHENA_SC__PLUGIN_DIR', plugin_dir_path( __FILE__ ) );

// Shortcode files
include_once 'includes/class-shortcode.php';
include_once 'shortcodes/shortcodes.php';

include_once 'includes/athena-sc-config.php';
include_once 'includes/athena-sc-tinymce-config.php';


if ( ! function_exists( 'athena_sc_plugin_activated' ) ) {
	function athena_sc_plugin_activated() {
		return;
	}

	register_activation_hook( ATHENA_SC__PLUGIN_FILE, 'athena_sc_plugin_activated' );
}

if ( ! function_exists( 'athena_sc_plugin_deactivated' ) ) {
	function athena_sc_plugin_deactivated() {
		return;
	}

	register_deactivation_hook( ATHENA_SC__PLUGIN_FILE, 'athena_sc_plugin_deactivated' );
}

if ( ! function_exists( 'athena_sc_init' ) ) {
	function athena_sc_init() {
		// Add our preconfigured shortcodes.
		add_action( 'athena_sc_add_shortcode', array( 'ATHENA_SC_Config', 'athena_sc_add_shortcode' ), 10, 1 );
		// Update the_content to strip excess <p></p> and <br> insertion around
		// Athena shortcodes.
		add_filter( 'the_content', array( 'ATHENA_SC_Config', 'format_shortcode_output' ), 10, 1 );
		// Hook into ACF's custom field filtering hooks to strip excess
		// <p></p> and <br> insertion around shortcodes in WYSIWYG fields.
		if ( class_exists( 'acf' ) ) {
			add_filter( 'acf/format_value/type=wysiwyg', array( 'ATHENA_SC_Config', 'format_acf_wysiwyg_output' ), 99, 3 );
		}
		// Register our shortcodes.
		add_action( 'init', array( 'ATHENA_SC_Config', 'register_shortcodes' ) );

		// If the `WP-Shortcode-Interface` plugin is installed, add the definitions.
		if ( class_exists( 'WP_SCIF_Config' ) ) {
			add_action( 'wp_scif_add_shortcode', array( 'ATHENA_SC_Config', 'register_shortcodes_interface' ), 10, 1 );
			add_action( 'wp_scif_get_preview_stylesheets', array( 'ATHENA_SC_Config', 'register_shortcodes_preview_styles' ), 10, 1 );
		}

		// Allow shortcodes within text widgets.
		add_filter( 'widget_text', 'do_shortcode' );
	}

	add_action( 'plugins_loaded', 'athena_sc_init' );
}

if ( ! function_exists( 'athena_sc_tinymce_init' ) ) {
	function athena_sc_tinymce_init() {
		$options_enabled = apply_filters( 'athena_sc_enable_tinymce_formatting', false );
		if ( $options_enabled ) {
			// Enqueue TinyMCE styles.
			add_editor_style( plugins_url( 'static/css/athena-editor-styles.min.css', ATHENA_SC__PLUGIN_FILE ) );
			// Enable custom TinyMCE formats.
			add_filter( 'mce_buttons_2', array( 'ATHENA_SC_TinyMCE_Config', 'enable_formats' ) );
			// Register custom formatting options with TinyMCE.
			add_action( 'tiny_mce_before_init', array( 'ATHENA_SC_TinyMCE_Config', 'register_settings' ) );

			// Override classes added to <img> tags generated by WordPress.
			add_filter( 'get_image_tag_class', array( 'ATHENA_SC_TinyMCE_Config', 'format_image_output_classes' ), 10, 4 );
			// Modify generated markup for images in post content.
			add_filter( 'the_content', array( 'ATHENA_SC_TinyMCE_Config', 'format_image_output' ) );
			// Override the default caption shortcode to apply Athena classes.
			add_filter( 'img_caption_shortcode', array( 'ATHENA_SC_TinyMCE_Config', 'format_caption_shortcode' ), 10, 3 );
		}
	}

	add_action( 'init', 'athena_sc_tinymce_init' );
}

?>
