<?php
/**
 * Logic related to markup generated for WordPress oEmbeds
 **/
if ( ! class_exists( 'ATHENA_SC_Embed_Config' ) ) {
	class ATHENA_SC_Embed_Config {

		/**
		 * Updates oEmbed video markup generated by WordPress to be
		 * wrapped in a responsive wrapper div.
		 *
		 * Intended for use on the `oembed_dataparse` hook.
		 *
		 * @since 0.4.0
		 * @author Jo Dickson
		 * @param string $html The returned oEmbed HTML.
		 * @param object $data A data object result from an oEmbed provider.
		 * @param string $url The URL of the content to be embedded.
		 * @return mixed Modified oEmbed HTML string
		 */
		public static function wrap_responsive_videos( $html, $data, $url ) {
			if ( $data->type === 'video' ) {
				return '<div class="embed-responsive embed-responsive-16by9">' . $html . '</div>';
			}
			return $html;
		}

	}
}
